# Generated by Django 5.2.7 on 2025-11-05 15:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Relacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('primerApellido', models.CharField(max_length=50)),
                ('segundoApellido', models.CharField(blank=True, max_length=50)),
                ('alias', models.CharField(blank=True, max_length=50)),
                ('telefono', models.CharField(max_length=10, unique=True)),
                ('correo', models.EmailField(blank=True, max_length=254, unique=True)),
                ('relacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='agenda.relacion')),
            ],
        ),
    ]
